/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <cstdint>
#include <cstdio>

#include "Src/bitapi/stm32f407_utils.hpp"
#include "drivers/gpio.hpp"
#include "drivers/util.hpp"

using namespace Stm32f407::Driver;
using namespace Stm32f407;

int main(void)
{
    // printf("Hello Wordl!\n");
    auto gpioD = GpioD{};
    auto& pin12 = gpioD.pin12();
    pin12.setMode(GpioMode::Output);
    pin12.setOutputType(GpioOutputType::PushPull);
    pin12.setOutputSpeed(GpioOutputSpeed::Low);
    pin12.setPupd(GpioPupd::NoPull);

    auto gpioA = GpioA{};
    auto& pin0 = gpioA.pin0();
    pin0.setMode(GpioMode::Input);
    // pin0.setOutputType(GpioOutputType::PushPull);
    // pin0.setOutputSpeed(GpioOutputSpeed::Low);
    pin0.setPupd(GpioPupd::NoPull);

    // pin0.configureInterruptMode(GpioInterruptMode::RisingAndFallingEdge, GpioPupd::NoPull);

    while (true)
    {
        if (pin0.readInput() == Common::PinState::High)
        {
            if (pin12.readOutput() == Common::PinState::Low)
            {
                pin12.writeOutput(Common::PinState::High);
            }
        }
        else
        {
            if (pin12.readOutput() == Common::PinState::High)
            {
                pin12.writeOutput(Common::PinState::Low);
            }
        }
    }
}
